# tell TravisCI we need a copy of docker running
# build our image using Dockerfile.dev
# tell TravisCI how to run our test suite
# tell TravisCI how to deploy our code to AWS
language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-907993406085"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $access_key
  secret_access_key: $aws_secret_key